[package]
name = "rustcss"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav.panferov@revjet.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs= "1.1.1"
web-sys={ version = "0.3.39", optional=true, features = [
  "StyleSheet",
  "Document",
  "Text",
  "Element"
] }

[features]
default=[]
dom=["web-sys"]
