[package]
name = "ruvie-css"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav.panferov@revjet.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs= "1.1.1"
web-sys={ version = "0.3.39", optional=true, features = [
  "StyleSheet",
  "Document",
  "Text",
  "Element"
] }

[build-dependencies]
serde = {version="*", features=["derive"]}
serde_json = "*"
quote = "1.0.7"
nom="6.0.0-alpha1"
Inflector="*"
proc-macro2="*"

[features]
default=[]
dom=["web-sys"]
