
[workspace]
members = [
    "packages/rustweb",
    "packages/rustcss",
    "examples/simple",
]

# [profile.release]
# # This makes the compiled code faster and smaller, but it makes compiling slower,
# # so it's only enabled in release mode.
# lto = true