[package]
name = "ruvie"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav.panferov@revjet.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs="^1.1"
observe={path = "../../../observe/packages/observe"}
ruvie-css={path = "../ruvie-css", optional=true}
snowflake = "^1.3"
fxhash="^0.2"
parking_lot="^0.11"
indexmap="^1.4"
harsh={version="^0.2"}
anyhow="^1"
thiserror="^1"

# STATIC
html5ever={version="^0.25", optional=true}
markup5ever={version="^0.10", optional=true}
markup5ever_rcdom={version="^0.1", optional=true}

# DOM:
js-sys= {version="^0.3", optional=true}
wasm-bindgen= {version = "^0.2", optional=true}
console_error_panic_hook = {version="^0.1", optional=true}
web-sys = { version = "^0.3", optional=true, features = [
  "console",
  "DocumentFragment",
  'Document',
  'Comment',
  'Element',
  'HtmlStyleElement',
  'HtmlHeadElement',
  'HtmlCollection',
  "Text",
  'HtmlElement',
  'InputEvent',
  'MouseEvent',
  'Node',
  'Window',
  'Range'
] }

[features]
default=["web", "ssr", "css"]
css = ["ruvie-css"]
web = ["js-sys", "web-sys", "wasm-bindgen", "console_error_panic_hook"]
ssr = ["html5ever", "markup5ever_rcdom", "markup5ever"]

[dev-dependencies]
criterion = "0.3"
rand={version= "^0.7", features = ["wasm-bindgen"]}
wasm-bindgen-test = "^0.3"

# [[bench]]
# name = "diff"
# harness = false