[package]
name = "rustweb"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav.panferov@revjet.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs= "1.1.1"
observe={path = "../../../observe"}
rustcss={path = "../rustcss"}
lis="*"
snowflake = "1.3.0"

# DOM:

js-sys= {version="0.3.39", optional=true}
wasm-bindgen= {version = "0.2.62", optional=true}
console_error_panic_hook = {version="0.1.6", optional=true}
web-sys = { version = "0.3.39", optional=true, features = [
  "console",
  "DocumentFragment",
  'Document',
  'Comment',
  'Element',
  "Text",
  'HtmlElement',
  'InputEvent',
  'Node',
  'Window',
] }

[features]
default=[]
dom = ["js-sys", "web-sys", "wasm-bindgen", "console_error_panic_hook"]

[dev-dependencies]
criterion = "0.3"
rand="*"

[[bench]]
name = "diff"
harness = false