[package]
name = "rustweb"
version = "0.1.0"
authors = ["Stanislav Panferov <stanislav.panferov@revjet.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen= "0.2.60"
console_error_panic_hook = "0.1.6"
observe={path = "../../../observe", features=["wasm-bindgen-futures-0"]}
rustcss={path = "../rustcss"}
js-sys= "0.3.37"
snowflake = "1.3.0"
web-sys={ version = "0.3.37", features = [
  "console",
  "DocumentFragment",
  'Document',
  'Comment',
  'Element',
  "Text",
  'HtmlElement',
  'Node',
  'Window',
] }
